### ISSUE TITLE
Detailed information about deploy

### ISSUE THREAD

**Issue by Skystapper** [0xF6/NovelAI-Telegram-Bot#1]
Sorry but, I didn't exactly understood how to set up this repo. Can you provide me some more details about it, like how can I set this up on Google colab, which environment variables will be necessary. Sorry, but I am kinda new to this thing 😅.

**Comment by 0xF6** [comment]
What

**Comment by 0xF6** [comment]
What does Google Colaboratory have to do with it?

**Comment by Skystapper** [comment]
Oh, sorry about that 🙇🏻. I just assumed that it would be on Google colab because I have seen some repos about stable diffusion where the devs have given the option to set it up on Google colab.

On which platform it is meant to be deployed, on VPS or any other online service like heroku?

**Comment by 0xF6** [comment]
It doesn't matter where you want it to be deployed.
But you need an account in google cloud (with payed subscribe) with firebase enabled, and a novelai account
