### ISSUE TITLE
How to deploy a project locally without google credit and FIRESTORE?

### ISSUE THREAD

**Issue by TimmekHW** [0xF6/NovelAI-Telegram-Bot#2]
I have an extra computer. I want to make the NAI bot work on it for myself and my friends. Is it possible without Google credit and Firestore?

**Comment by 0xF6** [comment]
Yep, one of these days I will add switching to the local database, I just have a similar code in another project.

**Comment by 0xF6** [comment]
Btw, NovelAI updated API and added encryption (decryptor writed in wasm) of images received from the server, so the code update will be delayed~

**Comment by TimmekHW** [comment]
> Btw, NovelAI updated API and added encryption (decryptor writed in wasm) of images received from the server, so the code update will be delayed~

I noticed that I get this from my bot:
Произошла ошибка: 200 - PK        �HtW�g����  ��      image_0.png�PNG
 
   IHDR             �x��    tEXtTitle AI generated image��R�    tEXtDescription 1girl H��    tEXtSoftware NovelAI�]��   #tEXtSource Stable Diffusion XL C1E1DE52DD a   !tEXtGeneration time 4.323387079872191$QTC   ?tEXtComment {"prompt": "1girl", "steps": 28, "height": 512, "width": 512, "scale": 7.0, "uncond_scale": 0.0, "cfg_rescale": 0.0, "seed": 261, "n_samples": 1, "hide_debug_overlay": false, "noise_schedule": "native", "sampler": "k_euler_ancestral", "controlnet_strength": 1.0, "controlnet_model": null, "dynamic_thresholding": false, "dynamic_thresholding_percentile": 0.999, "dynamic_thresholding_mimic_scale": 10.0, "sm": false, "sm_dyn": false, "skip_cfg_below_sigma": 0.0, "lora_unet_weights": null, "lora_clip_weights": null, "uc": "", "request_type": "PromptGenerateRequest"}ҳ�    IDATx���w�e�}߇~v:���y�{�'  3 d� I� � $>� �d+�iyY����,[����޲�l?=>ɒ(�2i� 3H� I    q�09��t�|�9g��ǹU]�&a�4�ӫ�n�tn�S{�����O��", R�;� � ��� �7|Z$"�z,^�Y/����~���"�s���t�    �+~���� ���ˏ�kN�Nsܽ�� �F��F牗����}��> �z��g]}�_��^��L_ w�_����~�|,^�T��9�˾����{� W��r���F��x�u �Ǹ�_�k���r�c_}�[ŵsR} v��޿���_/�ޯ�o�������]�7��_� ] q�����W���s�^���kq����'�ѧ�z���ox��^=�ԯg����J�� �/��<;�L��k�RL�-���+ϰ��h� #B B  @D�U`���5o�_���F�M��c}3�����F^� �-7���w� �>�>�WxNCCë獞�� ��뱸_��q=�L�x�z�[
D�1
B��m��L�o��u#����n��W�y��c3�V �3��㿖����-�h�~���^������u��J�ɫ�/���t�+�r���~�o�'��[��;��u������!�����1wy�_� ��Z C�Q�(.O}o� �;|_yr�� ���V�tҿ� ��=~�1���?� �������0�~�Wk �����m�����^�8u�]�_�+���;�o�|�Z �o$���7ڶ���:��Js�!ry���9,� f��� 1  w���  �J�Q�� ��{U����$ �F���Ȉ�ռ���{o��^.��p}�s��΍� y�g.��g�z���jm ��hfCCCCCC÷ _Ϯ]�k���+  �&��ݻ����I� o:��C�7|��� Q\?�  C�������ۊW^�_]f���W?�Y�      �#� ���  ^�\�2�l�������������˫��{CCCCCC÷5b��� ���  $�V 4444444|GqY��F ��O� ��W m< � \#lw#E�� ��  7~vCC�w ����fK}4�ņ�o$���b�=Wk�� ��N��K lFkC�w4�d�3m�iur�WMA�4�����2��ގ$S7��Ϋ /@C�w ;� �ռ�އĵ��Bo܈�� �O #� �d4&MJ�k����i��  ^ /�)આpQ�� �
W544| s�@�W�  q���[ߌӎ��� �/�����n�� �BP x�ѧY���Rr��ןj�ſ������O\��+�*���z�hhh���ʁ b@ ID0.
��Cl D�O�O� ���Ǹw9~%Q�W���K
  =� �Iž}˵q05F�ԣ�����5z� ]s}�A3"  ���� /ﱉ!N ����յM~���=���Q��[n��C  q�7�����@_G�{� ;  �:��0���*��� ��6�� I� B@L��D �v2ohh� se @��x�& ���m��5�E� �( J*�t%][������_��_�r�v��C ?N1)�����S�r������p�=����8��� �m �D RH�
��k�8wa��O `i����~� �8 v}1"���   �Q� c �  6�~C÷ W/�� �R A �я|�O�� ��� ��� y���8|� ?��?� �x �5� }��/���]�7����s���ỿ� |�C��-Ǐ_���j��v�  ��Bp�o���"�妅6w Ydv����q� u 2y�]�@d3�44� ^ώ]� �eG�5�f464|   H$��ࡇ����g���  �|�;�Ї?� ����r�83�3  P��F���/�[� ���<��#�>s�N'���������_��{6xo��Zb�S   ɳ  ~�3O���!� -�]Gg9����J1�B$ !��#!�20� �hhhx%^� 0� �� h�   ^�� � W�������;G���|����'�|�[n>� ���������p�}� �  1 v< Zk�}�$_�� �� �1:� �Q�#�<ί����~����?���W��Orx����4�,> 
 �� ���*���?a����w��� �0 F��&� st f �F YO7S/� � ����e�  1� No79 W  g R����w���iq�=�_~�x� ۩��u��ν���������G>�]w���w�+����P�G�����s/p˭�`�G  �'8�H�����O�� p�[n玻gD! 1 ��ɧ������ ���u�]�W���� x�4I�z   �������' ⳟ��e�� ���y�[�+G��N(��R�[��3�E�� �^� BR� ĞI�  44|S�� �� D��oh�!1F�� ��v'CH�! E�\L����Zc�j�����U�����l��|�������J/7���x׻�M+� ��O��n[�ǟ�y�p0bks��`�`k���~N>�<Y��_���
�~�+����bia 5MƓZPV�O�������E.�������� �/pp�>�40 �- x�����>���aT+�?�����~�=,d ��
  %A�H�J�g��� U�; v���*���?744|C�c �e��� �а��&\� � �7'�^\'��av�KnسDƫ��W_� �y�G
ɤ �S������/� � ��� <r g â���_�� �O8~�f~� ��� l�'�*қ��lw � �|�q9fkm�����p����ȁ%f� � �gfv �hFÂ_�w��/��_���'�� � ����q <��Y>�'���#' h��w��_�����Yl9�  �U� 
�R$ -"y;%��H�j ���?5�  4^���o8;!�=�a����p5qgev �$F�ʹM���9.�&t�f�wt���fX� Z  { ҵ�8jQ v �w�pwj�WW.��~�_���}���7����_�!��  �l ���/~��O���O � ke�����|��� 8|��Gn�ǟ�ْ �� �˿�K�{�9Z���
[l�t����� ~�O�Ç��2A*�C_{���O�  {�4s7��� ���'��w��.�ҏ}  x�ʹ��W��-18� e B ��$���H� �h����_�� q9 Є   �9� @��� ��ǿ ����ێ �m�G  H���9=�3_z�/�p���@�Z�[�8q�É}- /�X�˙ie��P�o\��?=  ���'�_���3�k��?�����;����: ~�  ��W8s�  ~� !����w �B� ����gD�"D�T` "
b �Pa}I1th (�}� �l��B���q�~>�� ��� �z�8�IX]_�����Ǿ� J�sha���g��?�����b��� &� o=i'#��$K  ��@
Oo�C�ΐZ�� `�9����  � D�1 � �x�zߌ ���c�� !��� �y6� _x� ���y��D��"8O�'M y&��&,�f �m���,�[$Z�� �<E1���̧���U~�g������

**Comment by TimmekHW** [comment]
> Btw, NovelAI updated API and added encryption (decryptor writed in wasm) of images received from the server, so the code update will be delayed~

there is no encryption, just now the server sends a .zip file instead of a .png

**Comment by 0xF6** [comment]
> there is no encryption, just now the server sends a .zip file instead of a .png  

Yes, I've already found out. encryption is used there for storyteller and keybox.
Anyway I'm doing an update~

**Comment by 0xF6** [comment]
I have updated bot and documentation, if something is not clear, please contact~
